# YOUR NAME OR TITLE OF YOUR SITE
name: OmniCafé

# YOUR BRAND/PERSONAL TAGLINE
tagline: Your one-stop-shop for all OmniCafé brands.

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/cafeologista.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # 17miles
  - Name: 17miles coffee roasters
    URL: https://www.17milescoffeeroasters.com
    Color: '#ff0000'
    Icon-Class: fab fa-globe

    # javamax
  - Name: JavaMax
    URL: https://www.javamax.com
    Color: '#7e5050'
    Icon-Class: fab fa-website

    # webrew
  - Name: weBREW Solutions
    URL: https://webrew.solutions
    Color: '#ec6cc0'
    Icon-Class: fab fa-website

     # cafeologista
  - Name: Cafeologista
    URL: cafeologista.github.io
    Color: '#000000'
    Icon-Class: fa-brands fa-website

    # email
  - Name: Email
    URL: 'mailto:omnicafe@gmail.com'
    Color: '#000000'
    Icon-Class: fab fa-envelope

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 'https://buymeacoffee.com'
    Username: cafeologista
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'


# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
